apiVersion: webapp.simpletest.com/v1alpha1
kind: Webapp
metadata:
  name: webapp-sample
  labels:
    app: guestbook-ui
spec:
  storageaccountname: "test-storage-account"
  azuresubscriptionid: "ppp"
  webappversion: "v1.2.10"

